[env]
TERM = "xterm-256color"

[font]
size = 16.0
offset = { y = 1 }
normal = { family = "Jetbrains Mono NL", style = "medium" }


[terminal.shell]
program = "/bin/fish"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"

[keyboard]
bindings = [ 
    { key = "Q", mods = "Control | Shift", action = "Quit" } 
]


# # These two keyboard bindings are to make Shift/Control + Enter work in Nvim
# [[keyboard.bindings]]
# chars = "\u001B[13;2u"
# key = "Return"
# mods = "Shift"

# [[keyboard.bindings]]
# chars = "\u001B[13;5u"
# key = "Return"
# mods = "Control"
#
# [[keyboard.bindings]]
# key = "Q"
# mods = "Control"
# action = "Quit"


