[env]
TERM = "xterm-256color"

[font]
size = 14.0
offset = { y = 1 }
normal = { family = "Jetbrains Mono NL", style = "medium" }


[shell]
program = "/bin/fish"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"
# opacity = 0.9

